### ISSUE TITLE
binder_linux not found

### ISSUE THREAD

**Issue by bdodroid** [sailfishos-open/waydroid#22]
Trying to get this running on a pinephone pro and I cant seem to get around this "binder_linux not found" error.
Running "waydroid init" just spits out:
```
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.0.7-pinephonepro
ERROR: Binder node "binder" for waydroid not found 
```

Is there a way I can install binder_linux on sailfish? did I miss a package somewhere?

**Comment by piggz** [comment]
This is probably a pinephone pro port bug, not a waydroid/packaging bug.  Please log an issue on this repo so i dont forget :) https://github.com/sailfish-on-dontbeevil/kernel-adaptation-pinephonepro
