### ISSUE TITLE
Proposal to remove gbinder config files

### ISSUE THREAD

**Issue by piggz** [sailfishos-open/waydroid#23]
I propose to remove the packaging of the gbinder config files from the project.  This is for the following reasons:
1) Devices can have different binder nodes, we currently cover 2 cases but some hybris ports have different node names such the anbox* prefix
2) On hybris18 based devices, the aidl version needs changed to 3 from 2, which makes packaging more complicated if we need to support different combinations
3) Current waydroid does not need the config files if using an up to date gbinder (https://github.com/waydroid/waydroid/commit/75aa5c96f2d755eba9f33cda48ffd6f173512c0b)

For best support, porters would need to to update gbinder (https://github.com/mer-hybris/libgbinder/pull/93), until a newer version is shipped with sailfish, i wouldnt propose adding this to chum as its against our policy.

So, porters would have 2 options
1)Update gbinder in the device repo
2)Add the gbinder config file appropriate for their device to the device config repo

If users are experimenting on their device, we can have instructions on how to write the config.

**Comment by rinigus** [comment]
It sounds reasonable. So, when gbinder of SFOS will catch up with the current "latest" one, no configs will be needed at all, right? Which means that we have to figure out how to manage it until its done.

In principle, we could just remove  `waydroid-gbinder-config` requirement but keep making config packages here for typical devices ("regular" hybris and mainline). Then we don't have to change on ports side and just instruct users to install these packages as needed. This messing with the port is a touch more difficult. Ideally, it would still be separate package as changes in droid-config would lead to updates in some other packages that depend on it.

**Comment by piggz** [comment]
Ok, that seems like a reasonable compromise.  Remove requirement to install package, leave packages available and update docs to match?
I will work up a PR for this.

**Comment by rinigus** [comment]
Great, thank you very much!
