### ISSUE TITLE
No Bluetooth-Support

### ISSUE THREAD

**Issue by FingusDE** [sailfishos-open/waydroid#26]
Bluetooth Icon ist turned off and Apps can´t turn it on.

**Comment by rinigus** [comment]
Is it supported by Waydroid itself? Not sure whether it is SFOS packaging or Waydroid upstream issue

**Comment by piggz** [comment]
It isnt.  See https://github.com/waydroid/waydroid/issues/155 ... I will close this as its not realistic for use to write an android-bt -> bluez proxy here.
